In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Import Data

In [2]:
df = pd.read_csv('BankChurners.csv')
df.head()

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.99991
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.99994
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.99998
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.99987
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.99998

Dataset Understanding

In [3]:
df.isnull().sum()

CLIENTNUM                                                                                                                             0
Attrition_Flag                                                                                                                        0
Customer_Age                                                                                                                          0
Gender                                                                                                                                0
Dependent_count                                                                                                                       0
Education_Level                                                                                                                       0
Marital_Status                                                                                                                        0
Income_Category                                                                                                                       0
Card_Category                                                                                                                         0
Months_on_book                                                                                                                        0
Total_Relationship_Count                                                                                                              0
Months_Inactive_12_mon                                                                                                                0
Contacts_Count_12_mon                                                                                                                 0
Credit_Limit                                                                                                                          0
Total_Revolving_Bal                                                                                                                   0
Avg_Open_To_Buy                                                                                                                       0
Total_Amt_Chng_Q4_Q1                                                                                                                  0
Total_Trans_Amt                                                                                                                       0
Total_Trans_Ct                                                                                                                        0
Total_Ct_Chng_Q4_Q1                                                                                                                   0
Avg_Utilization_Ratio                                                                                                                 0
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1    0
Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2    0
dtype: int64

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.drop(columns=[
    "CLIENTNUM",
    "Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1",
    "Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"
], inplace=True)

In [6]:
df.describe()

,Customer_Age,Dependent_count,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
count,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000
mean,46.325960,2.346203,35.928409,3.812580,2.341167,2.455317,8631.953698,1162.814061,7469.139637,0.759941,4404.086304,64.858695,0.712222,0.274894
std,8.016814,1.298908,7.986416,1.554408,1.010622,1.106225,9088.776650,814.987335,9090.685324,0.219207,3397.129254,23.472570,0.238086,0.275691
min,26.000000,0.000000,13.000000,1.000000,0.000000,0.000000,1438.300000,0.000000,3.000000,0.000000,510.000000,10.000000,0.000000,0.000000
25%,41.000000,1.000000,31.000000,3.000000,2.000000,2.000000,2555.000000,359.000000,1324.500000,0.631000,2155.500000,45.000000,0.582000,0.023000
50%,46.000000,2.000000,36.000000,4.000000,2.000000,2.000000,4549.000000,1276.000000,3474.000000,0.736000,3899.000000,67.000000,0.702000,0.176000
75%,52.000000,3.000000,40.000000,5.000000,3.000000,3.000000,11067.500000,1784.000000,9859.000000,0.859000,4741.000000,81.000000,0.818000,0.503000
max,73.000000,5.000000,56.000000,6.000000,6.000000,6.000000,34516.000000,2517.000000,34516.000000,3.397000,18484.000000,139.000000,3.714000,0.999000

In [7]:
df.columns

Index(['Attrition_Flag', 'Customer_Age', 'Gender', 'Dependent_count',
       'Education_Level', 'Marital_Status', 'Income_Category', 'Card_Category',
       'Months_on_book', 'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio'],
      dtype='str')

In [8]:
df.rename(
    columns={
        "Customer_Age": "Age",
        "Income_Category": "Income_Group",
        "Total_Trans_Ct": "Transaction_Count"
    },
    inplace=True
)

In [9]:
df["Gender"]=df["Gender"].replace({"M": "Male", "F": "Female" })

In [10]:
df["Gender"].value_counts()
df

,Attrition_Flag,Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Group,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Transaction_Count,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,Existing Customer,45,Male,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,Existing Customer,49,Female,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,Existing Customer,51,Male,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,Existing Customer,40,Female,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,Existing Customer,40,Male,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,Existing Customer,50,Male,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,Attrited Customer,41,Male,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,Attrited Customer,44,Female,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,Attrited Customer,30,Male,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,Attrited Customer,43,Female,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [11]:
df.loc[df["Age"] < 30, "Age_Group"] = "Young"
df.loc[df["Age"] >= 30, "Age_Group"] = "Adult"
df.loc[df["Age"] >= 60, "Age_Group"] = "Senior"

In [12]:
df["Churn_Flag"] = 0
df.loc[
    df["Attrition_Flag"] == "Attrited Customer",
    "Churn_Flag"
] = 1;

df["Churn_Flag"].value_counts()

Churn_Flag
0    8500
1    1627
Name: count, dtype: int64

In [13]:
df["Attrition_Flag"] = df["Attrition_Flag"].str.title()

export clean dataset

In [14]:
df.to_csv(
    "BankChurners_Cleaned.csv",
    index=False
)

Exploratory Data Analysis (EDA)

Total customer dataset

In [15]:
len(df)

10127

How many customer are still with the bank

In [16]:
df["Attrition_Flag"].value_counts()

Attrition_Flag
Existing Customer    8500
Attrited Customer    1627
Name: count, dtype: int64

churn rate

In [17]:
df["Attrition_Flag"].value_counts(normalize=True)*100

Attrition_Flag
Existing Customer    83.934038
Attrited Customer    16.065962
Name: proportion, dtype: float64

How many customers belong to each gender?

In [18]:
gender_counts=df.groupby("Gender").size()
print(gender_counts)

Gender
Female    5358
Male      4769
dtype: int64

What is the average age of Female vs Male customers

In [20]:
df.groupby("Gender")["Age"].mean()

Gender
Female    46.456887
Male      46.178863
Name: Age, dtype: float64

churned customers in each gender group.

In [21]:
df.groupby("Gender")["Churn_Flag"].sum()

Gender
Female    930
Male      697
Name: Churn_Flag, dtype: int64

Percentage of Male and female churned

In [22]:
churn_rate = (
    df.groupby("Gender")["Churn_Flag"].sum()
    / df.groupby("Gender").size()
    * 100
)
print(churn_rate)

Gender
Female    17.357223
Male      14.615223
dtype: float64

summary of our customers by gender

In [23]:
df.groupby("Gender").agg({
    "Age": ["mean", "min", "max"],
    "Credit_Limit": ["mean", "min", "max"]
})

              Age          Credit_Limit
             mean min max          mean     min      max
Gender
Female  46.456887  26  67   5023.854274  1438.3  34516.0
Male    46.178863  26  73  12685.674963  1438.3  34516.0

What are the minimum, maximum, and average credit limits for each gender?

In [24]:
df.groupby("Gender").agg({
    "Credit_Limit": ["mean", "min", "max"]
})

        Credit_Limit
                mean     min      max
Gender
Female   5023.854274  1438.3  34516.0
Male    12685.674963  1438.3  34516.0

In [25]:
df.groupby("Gender").agg({"Card_Category": "value_counts"})

                      Card_Category
Gender Card_Category
Female Blue                    5101
       Silver                   210
       Gold                      38
       Platinum                   9
Male   Blue                    4335
       Silver                   345
       Gold                      78
       Platinum                  11

In [26]:
df["Education_Level"].value_counts()

Education_Level
Graduate         3128
High School      2013
Unknown          1519
Uneducated       1487
College          1013
Post-Graduate     516
Doctorate         451
Name: count, dtype: int64

Show customers who made more than 100 transactions.

In [27]:
high_transaction_customers = df[
    df["Transaction_Count"] > 100]
print(high_transaction_customers.shape)

(649, 22)

How many churned customers had more than 50 transactions?

In [28]:
churned_high_transaction = df[
    (df["Attrition_Flag"] == "Attrited Customer") &
    (df["Transaction_Count"] > 50)
]
print(churned_high_transaction.shape)

(440, 22)

Find the top 10 churned customers by transaction amount.

In [29]:
top_churned = (
    df[df["Attrition_Flag"] == "Attrited Customer"]
    .sort_values("Total_Trans_Amt", ascending=False)
    .head(10)
)
top_churned

,Attrition_Flag,Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Group,Card_Category,Months_on_book,Total_Relationship_Count,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Transaction_Count,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Age_Group,Churn_Flag
9946,Attrited Customer,44,Male,1,Uneducated,Married,$40K - $60K,Blue,34,5,...,10973.0,0,10973.0,0.792,10583,75,0.786,0.000,Adult,1
10108,Attrited Customer,47,Male,4,Graduate,Divorced,$80K - $120K,Blue,39,4,...,17504.0,476,17028.0,0.892,10468,66,0.737,0.027,Adult,1
10118,Attrited Customer,50,Male,1,Unknown,Unknown,$80K - $120K,Blue,36,6,...,9959.0,952,9007.0,0.825,10310,63,1.100,0.096,Adult,1
10126,Attrited Customer,43,Female,2,Graduate,Married,Less than $40K,Silver,25,6,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,Adult,1
10124,Attrited Customer,44,Female,1,High School,Married,Less than $40K,Blue,36,5,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,Adult,1
10113,Attrited Customer,27,Male,0,High School,Divorced,$60K - $80K,Blue,36,2,...,13303.0,2517,10786.0,0.929,10219,85,0.809,0.189,Young,1
9822,Attrited Customer,29,Male,0,High School,Single,$40K - $60K,Blue,36,6,...,5988.0,660,5328.0,1.041,10211,68,1.000,0.110,Young,1
9458,Attrited Customer,37,Male,2,Uneducated,Unknown,$80K - $120K,Blue,18,1,...,31832.0,518,31314.0,0.972,10201,59,0.788,0.016,Adult,1
10105,Attrited Customer,59,Female,1,High School,Married,Less than $40K,Blue,50,1,...,5043.0,743,4300.0,0.805,10170,66,0.784,0.147,Adult,1
9968,Attrited Customer,51,Female,1,Graduate,Married,Unknown,Silver,44,4,...,33004.0,2418,30586.0,0.923,10156,72,0.946,0.073,Adult,1

In [30]:
df.query(
    "Age > 50 and Transaction_Count < 50"
)

,Attrition_Flag,Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Group,Card_Category,Months_on_book,Total_Relationship_Count,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Transaction_Count,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Age_Group,Churn_Flag
2,Existing Customer,51,Male,3,Graduate,Married,$80K - $120K,Blue,36,4,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,Adult,0
6,Existing Customer,51,Male,4,Unknown,Married,$120K +,Gold,46,6,...,34516.0,2264,32252.0,1.975,1330,31,0.722,0.066,Adult,0
11,Existing Customer,65,Male,1,Unknown,Married,$40K - $60K,Blue,54,6,...,9095.0,1587,7508.0,1.433,1314,26,1.364,0.174,Senior,0
12,Existing Customer,56,Male,1,College,Single,$80K - $120K,Blue,36,3,...,11751.0,0,11751.0,3.397,1539,17,3.250,0.000,Adult,0
14,Existing Customer,57,Female,2,Graduate,Married,Less than $40K,Blue,48,5,...,2436.0,680,1756.0,1.190,1570,29,0.611,0.279,Adult,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9135,Attrited Customer,58,Male,2,Unknown,Single,$60K - $80K,Blue,48,2,...,2236.0,710,1526.0,0.434,2562,38,0.462,0.318,Adult,1
9149,Attrited Customer,56,Female,1,College,Single,Less than $40K,Blue,48,4,...,2783.0,1763,1020.0,0.344,3967,42,0.400,0.633,Adult,1
9194,Attrited Customer,51,Female,3,Uneducated,Married,Less than $40K,Blue,46,5,...,3536.0,0,3536.0,0.542,3281,39,0.393,0.000,Adult,1
9201,Attrited Customer,62,Female,0,Uneducated,Single,Less than $40K,Blue,36,6,...,5780.0,0,5780.0,0.394,6613,40,0.429,0.000,Senior,1
9776,Attrited Customer,52,Male,2,Graduate,Divorced,$80K - $120K,Silver,44,4,...,34516.0,751,33765.0,0.357,5806,40,0.429,0.022,Adult,1

Show average credit limit for each gender and card category.

In [31]:
df.pivot_table(
    values="Credit_Limit",
    index="Gender",
    columns="Card_Category",
    aggfunc="mean"
)

Card_Category          Blue          Gold      Platinum        Silver
Gender
Female          4308.064928  20967.000000  26280.888889  18614.752381
Male           10959.443806  32045.551282  33558.272727  29333.626087

In [32]:
df.groupby(
    ["Gender", "Attrition_Flag"]
)["Transaction_Count"].mean()

Gender  Attrition_Flag
Female  Attrited Customer    44.051613
        Existing Customer    71.036134
Male    Attrited Customer    46.110473
        Existing Customer    66.102407
Name: Transaction_Count, dtype: float64

Income Group vs Churn

In [33]:
income_churn = (
    df.groupby("Income_Group")["Churn_Flag"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

income_churn

Income_Group
$120K +           17.331499
Less than $40K    17.186184
Unknown           16.816547
$80K - $120K      15.765472
$40K - $60K       15.139665
$60K - $80K       13.480742
Name: Churn_Flag, dtype: float64

Age group vs Churn

In [34]:
age_churn = (
    df.groupby("Age_Group")["Churn_Flag"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

age_churn

Age_Group
Adult     16.372340
Senior    13.345865
Young      8.717949
Name: Churn_Flag, dtype: float64

Does the type of credit card a customer holds relate to their churn rate?

In [36]:
card_churn = (
    df.groupby("Card_Category")["Churn_Flag"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

card_churn

Card_Category
Platinum    25.000000
Gold        18.103448
Blue        16.097923
Silver      14.774775
Name: Churn_Flag, dtype: float64

Do churned customers have different transaction activity compared with existing customers?

In [37]:
transaction_churn = (
    df.groupby("Attrition_Flag")["Transaction_Count"]
    .agg(["mean", "median", "min", "max"])
)

transaction_churn

                        mean  median  min  max
Attrition_Flag
Attrited Customer  44.933620    43.0   10   94
Existing Customer  68.672588    71.0   11  139

Do churned customers have different transaction spending behavior?

In [38]:
amount_churn = (
    df.groupby("Attrition_Flag")["Total_Trans_Amt"]
    .agg(["mean", "median", "min", "max"])
)

amount_churn

                          mean  median  min    max
Attrition_Flag
Attrited Customer  3095.025814  2329.0  510  10583
Existing Customer  4654.655882  4100.0  816  18484

Does customer inactivity relate to churn?

In [39]:
inactive_churn = (
    df.groupby("Months_Inactive_12_mon")["Churn_Flag"]
    .agg(["count", "sum", "mean"])
)

inactive_churn["Churn_Rate_%"] = inactive_churn["mean"] * 100

inactive_churn

                        count  sum      mean  Churn_Rate_%
Months_Inactive_12_mon
0                          29   15  0.517241     51.724138
1                        2233  100  0.044783      4.478280
2                        3282  505  0.153870     15.386959
3                        3846  826  0.214769     21.476859
4                         435  130  0.298851     29.885057
5                         178   32  0.179775     17.977528
6                         124   19  0.153226     15.322581

Does credit card utilization differ between existing and churned customers?

In [40]:
utilization_churn = (
    df.groupby("Attrition_Flag")["Avg_Utilization_Ratio"]
    .agg(["mean", "median", "min", "max"])
)

utilization_churn

                       mean  median  min    max
Attrition_Flag
Attrited Customer  0.162475   0.000  0.0  0.999
Existing Customer  0.296412   0.211  0.0  0.994

Does the number of products/relationships a customer has with the bank relate to churn?

In [41]:
relationship_churn = (
    df.groupby("Total_Relationship_Count")["Churn_Flag"]
    .agg(["count", "sum", "mean"])
)

relationship_churn["Churn_Rate_%"] = (
    relationship_churn["mean"] * 100
)

relationship_churn

                          count  sum      mean  Churn_Rate_%
Total_Relationship_Count
1                           910  233  0.256044     25.604396
2                          1243  346  0.278359     27.835881
3                          2305  400  0.173536     17.353579
4                          1912  225  0.117678     11.767782
5                          1891  227  0.120042     12.004231
6                          1866  196  0.105038     10.503751

Does a change in transaction activity relate to customer churn?

In [42]:
transaction_change_churn = (
    df.groupby("Attrition_Flag")["Total_Ct_Chng_Q4_Q1"]
    .agg(["count", "mean", "median", "min", "max"])
)

transaction_change_churn

                   count      mean  median    min    max
Attrition_Flag
Attrited Customer   1627  0.554386   0.531  0.000  2.500
Existing Customer   8500  0.742434   0.721  0.028  3.714

Does a change in transaction amount differ between existing and churned customers?

In [43]:
amount_change_churn = (
    df.groupby("Attrition_Flag")["Total_Amt_Chng_Q4_Q1"]
    .agg(["count", "mean", "median", "min", "max"])
)

amount_change_churn

                   count      mean  median    min    max
Attrition_Flag
Attrited Customer   1627  0.694277   0.701  0.000  1.492
Existing Customer   8500  0.772510   0.743  0.256  3.397

Which numerical variables have the strongest relationship with customer churn?

In [44]:
numeric_cols = [
    "Age",
    "Credit_Limit",
    "Total_Revolving_Bal",
    "Avg_Open_To_Buy",
    "Total_Trans_Amt",
    "Transaction_Count",
    "Total_Ct_Chng_Q4_Q1",
    "Total_Amt_Chng_Q4_Q1",
    "Total_Relationship_Count",
    "Months_Inactive_12_mon",
    "Contacts_Count_12_mon",
    "Avg_Utilization_Ratio",
    "Churn_Flag"
]

corr = df[numeric_cols].corr()

churn_corr = (
    corr["Churn_Flag"]
    .drop("Churn_Flag")
    .sort_values()
)

churn_corr

Transaction_Count          -0.371403
Total_Ct_Chng_Q4_Q1        -0.290054
Total_Revolving_Bal        -0.263053
Avg_Utilization_Ratio      -0.178410
Total_Trans_Amt            -0.168598
Total_Relationship_Count   -0.150005
Total_Amt_Chng_Q4_Q1       -0.131063
Credit_Limit               -0.023873
Avg_Open_To_Buy            -0.000285
Age                         0.018203
Months_Inactive_12_mon      0.152449
Contacts_Count_12_mon       0.204491
Name: Churn_Flag, dtype: float64